version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=${DATABASE_URL:-postgresql://dev_user:dev_pass@localhost:5432/dev_db}
    depends_on:
      - db:
        condition: service_healthy
    

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    args:
        - POSTGRES_USER: ${POSTGRES_USER:-dev_user}
        - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_pass}
        - POSTGRES_DB: ${POSTGRES_DB:-dev_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      - test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-dev_user} -d ${POSTGRES_DB:-dev_db}"]
      - interval: 10s
      - timeout: 5s
      - retries: 5

volumes:
  postgres_data: